// Code generated by "stringer -type=Type"; DO NOT EDIT.

package ast

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ERROR-0]
	_ = x[EOF-1]
	_ = x[COMMENT-2]
	_ = x[MULTILINE_COMMENT-3]
	_ = x[DIRECTIVE-4]
	_ = x[IDENT-5]
	_ = x[INT-6]
	_ = x[HEX-7]
	_ = x[FLOAT-8]
	_ = x[RUNE-9]
	_ = x[STRING-10]
	_ = x[ADD-11]
	_ = x[SUB-12]
	_ = x[MUL-13]
	_ = x[DIV-14]
	_ = x[MOD-15]
	_ = x[AND-16]
	_ = x[BOR-17]
	_ = x[XOR-18]
	_ = x[LSH-19]
	_ = x[RSH-20]
	_ = x[BNT-21]
	_ = x[QUESTION-22]
	_ = x[ADD_ASSIGN-23]
	_ = x[SUB_ASSIGN-24]
	_ = x[MUL_ASSIGN-25]
	_ = x[DIV_ASSIGN-26]
	_ = x[XOR_ASSIGN-27]
	_ = x[BOR_ASSIGN-28]
	_ = x[MOD_ASSIGN-29]
	_ = x[LAND-30]
	_ = x[LOR-31]
	_ = x[NOR-32]
	_ = x[INC-33]
	_ = x[DEC-34]
	_ = x[EQL-35]
	_ = x[SEQ-36]
	_ = x[NEQ-37]
	_ = x[SNE-38]
	_ = x[LSS-39]
	_ = x[GTR-40]
	_ = x[ASSIGN-41]
	_ = x[NOT-42]
	_ = x[LEQ-43]
	_ = x[GEQ-44]
	_ = x[LPAREN-45]
	_ = x[LBRACK-46]
	_ = x[LBRACE-47]
	_ = x[COMMA-48]
	_ = x[PERIOD-49]
	_ = x[RPAREN-50]
	_ = x[RBRACK-51]
	_ = x[RBRACE-52]
	_ = x[SEMICOLON-53]
	_ = x[COLON-54]
	_ = x[DECL-55]
	_ = x[LAMBDA-56]
	_ = x[BREAK-57]
	_ = x[CONTINUE-58]
	_ = x[IF-59]
	_ = x[ELSE-60]
	_ = x[FOR-61]
	_ = x[WHILE-62]
	_ = x[RETURN-63]
	_ = x[IMPORT-64]
	_ = x[SWITCH-65]
	_ = x[CASE-66]
	_ = x[DEFAULT-67]
	_ = x[LET-68]
	_ = x[VAR-69]
	_ = x[CONST-70]
	_ = x[FUNCTION-71]
	_ = x[ENUM-72]
	_ = x[NULL-73]
	_ = x[UNDEFINED-74]
	_ = x[INTERFACE-75]
	_ = x[EXPORT-76]
	_ = x[NEW-77]
	_ = x[CLASS-78]
	_ = x[TRUE-79]
	_ = x[FALSE-80]
	_ = x[TRY-81]
	_ = x[CATCH-82]
	_ = x[FINALLY-83]
	_ = x[THROW-84]
}

const _Type_name = "ERROREOFCOMMENTMULTILINE_COMMENTDIRECTIVEIDENTINTHEXFLOATRUNESTRINGADDSUBMULDIVMODANDBORXORLSHRSHBNTQUESTIONADD_ASSIGNSUB_ASSIGNMUL_ASSIGNDIV_ASSIGNXOR_ASSIGNBOR_ASSIGNMOD_ASSIGNLANDLORNORINCDECEQLSEQNEQSNELSSGTRASSIGNNOTLEQGEQLPARENLBRACKLBRACECOMMAPERIODRPARENRBRACKRBRACESEMICOLONCOLONDECLLAMBDABREAKCONTINUEIFELSEFORWHILERETURNIMPORTSWITCHCASEDEFAULTLETVARCONSTFUNCTIONENUMNULLUNDEFINEDINTERFACEEXPORTNEWCLASSTRUEFALSETRYCATCHFINALLYTHROW"

var _Type_index = [...]uint16{0, 5, 8, 15, 32, 41, 46, 49, 52, 57, 61, 67, 70, 73, 76, 79, 82, 85, 88, 91, 94, 97, 100, 108, 118, 128, 138, 148, 158, 168, 178, 182, 185, 188, 191, 194, 197, 200, 203, 206, 209, 212, 218, 221, 224, 227, 233, 239, 245, 250, 256, 262, 268, 274, 283, 288, 292, 298, 303, 311, 313, 317, 320, 325, 331, 337, 343, 347, 354, 357, 360, 365, 373, 377, 381, 390, 399, 405, 408, 413, 417, 422, 425, 430, 437, 442}

func (i Type) String() string {
	if i >= Type(len(_Type_index)-1) {
		return "Type(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Type_name[_Type_index[i]:_Type_index[i+1]]
}
